// src/lib/mockPatient.js
// Use this for local testing by replacing the sessionStorage call in your verify-code route
// or by manually setting: sessionStorage.setItem("patientData", JSON.stringify(mockPatient))

export const mockPatient = {
  age: 67,
  gender: "male",
  shareNotes: true,
  hasActiveSubscription: true,

  advice: [
    {
      id: 1,
      category: "medication",
      title: "Vurder gjennomgang av inhalasjonsbehandling",
      text: "Pasienten rapporterer CAT-skår over 20 i 4 av siste 6 uker. Symptomkontroll virker utilstrekkelig — vurder om vedlikeholdsbehandlingen bør justeres, eller om pasienten har behov for opplæring i inhalasjonsteknikk.",
      date: "2026-04-22",
      severity: "medium",
    },
    {
      id: 2,
      category: "exacerbation",
      title: "Flere alvorlige forverringer registrert",
      text: "3 alvorlige forverringer siste 8 uker. Gjennomgå handlingsplan med pasienten og vurder profylaktisk behandling.",
      date: "2026-04-15",
      severity: "high",
    },
    {
      id: 3,
      category: "vaccination",
      title: "Vaksinasjonsstatus oppdatert",
      text: "Influensa, COVID-19, pneumokokk, herpes zoster, RSV og kikhoste — alle dokumentert innen anbefalt intervall.",
      date: "2026-04-23",
      severity: "low",
    },
    {
      id: 4,
      category: "lifestyle",
      title: "Lav fysisk aktivitet",
      text: "Gjennomsnittlig aktivitetsnivå har falt siste 4 uker. Vurder henvisning til lungerehabilitering eller fysioterapi.",
      date: "2026-04-10",
      severity: "medium",
    },
    {
      id: 5,
      category: "spirometry",
      title: "Spirometri viser fall i FEV1",
      text: "Siste måling viser FEV1 1.7 L, ned fra 2.0 L for 10 dager siden. Anbefales ny måling og vurdering.",
      date: "2026-04-24",
      severity: "high",
      source: "https://goldcopd.org/2024-gold-report/",
    },
  ],
  records: [
    {
      date: "2025-10-06",
      cat8: 14,
      cat8Cough: 2,
      cat8Phlegm: 2,
      cat8ChestTightness: 2,
      cat8Breathlessness: 2,
      cat8Activities: 2,
      cat8Confidence: 1,
      cat8Sleep: 2,
      cat8Energy: 1,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 3,
      weight: 82,
      note: "Følte meg litt bedre denne uken.",
      medicines: [1],
      medicinesAtc: ["R03AC02"],
      medicinesDoses: [2],
      medicinesUsedTimes: [3],
    },
    {
      date: "2025-10-13",
      cat8: 18,
      cat8Cough: 3,
      cat8Phlegm: 2,
      cat8ChestTightness: 3,
      cat8Breathlessness: 2,
      cat8Activities: 2,
      cat8Confidence: 2,
      cat8Sleep: 2,
      cat8Energy: 2,
      moderateExacerbations: true,
      seriousExacerbations: false,
      physicalActivity: 2,
      weight: 82,
      note: "",
      medicines: [1, 2],
      medicinesAtc: ["R03AC02", "R03BA02"],
      medicinesDoses: [2, 1],
      medicinesUsedTimes: [4, 1],
    },
    {
      date: "2025-10-20",
      cat8: 22,
      cat8Cough: 3,
      cat8Phlegm: 3,
      cat8ChestTightness: 3,
      cat8Breathlessness: 3,
      cat8Activities: 3,
      cat8Confidence: 2,
      cat8Sleep: 3,
      cat8Energy: 2,
      moderateExacerbations: false,
      seriousExacerbations: true,
      physicalActivity: 1,
      weight: 81,
      note: "Tung uke, måtte hvile mye.",
      medicines: [1, 2],
      medicinesAtc: ["R03AC02", "R03BA02"],
      medicinesDoses: [2, 1],
      medicinesUsedTimes: [7, 2],
    },
    {
      date: "2025-10-27",
      cat8: 16,
      cat8Cough: 2,
      cat8Phlegm: 2,
      cat8ChestTightness: 2,
      cat8Breathlessness: 2,
      cat8Activities: 2,
      cat8Confidence: 2,
      cat8Sleep: 2,
      cat8Energy: 2,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 2,
      weight: 81,
      note: "",
      medicines: [1],
      medicinesAtc: ["R03AC02"],
      medicinesDoses: [2],
      medicinesUsedTimes: [2],
    },
    {
      date: "2025-11-03",
      cat8: 12,
      cat8Cough: 2,
      cat8Phlegm: 1,
      cat8ChestTightness: 2,
      cat8Breathlessness: 1,
      cat8Activities: 2,
      cat8Confidence: 1,
      cat8Sleep: 2,
      cat8Energy: 1,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 3,
      weight: 82,
      note: "Bedre uke, kom meg ut og gikk litt.",
      medicines: [1],
      medicinesAtc: ["R03AC02"],
      medicinesDoses: [2],
      medicinesUsedTimes: [2],
    },
    {
      date: "2025-11-10",
      cat8: 9,
      cat8Cough: 1,
      cat8Phlegm: 1,
      cat8ChestTightness: 1,
      cat8Breathlessness: 1,
      cat8Activities: 1,
      cat8Confidence: 1,
      cat8Sleep: 2,
      cat8Energy: 1,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 3,
      weight: 82,
      note: "",
      medicines: [],
      medicinesAtc: [],
      medicinesDoses: [],
      medicinesUsedTimes: [],
    },
    {
      date: "2025-11-17",
      cat8: 8,
      cat8Cough: 1,
      cat8Phlegm: 1,
      cat8ChestTightness: 1,
      cat8Breathlessness: 1,
      cat8Activities: 1,
      cat8Confidence: 1,
      cat8Sleep: 1,
      cat8Energy: 1,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 3,
      weight: 83,
      note: "God uke!",
      medicines: [],
      medicinesAtc: [],
      medicinesDoses: [],
      medicinesUsedTimes: [],
    },
    {
      date: "2025-11-24",
      cat8: 11,
      cat8Cough: 2,
      cat8Phlegm: 1,
      cat8ChestTightness: 1,
      cat8Breathlessness: 2,
      cat8Activities: 1,
      cat8Confidence: 2,
      cat8Sleep: 1,
      cat8Energy: 1,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 3,
      weight: 83,
      note: "",
      medicines: [1],
      medicinesAtc: ["R03AC02"],
      medicinesDoses: [2],
      medicinesUsedTimes: [1],
    },
    {
      date: "2025-12-01",
      cat8: 20,
      cat8Cough: 3,
      cat8Phlegm: 2,
      cat8ChestTightness: 3,
      cat8Breathlessness: 2,
      cat8Activities: 3,
      cat8Confidence: 2,
      cat8Sleep: 3,
      cat8Energy: 2,
      moderateExacerbations: true,
      seriousExacerbations: false,
      physicalActivity: 2,
      weight: 81,
      note: "Forkjølet, litt ekstra hoste.",
      medicines: [1, 2],
      medicinesAtc: ["R03AC02", "R03BA02"],
      medicinesDoses: [2, 1],
      medicinesUsedTimes: [5, 1],
    },
    {
      date: "2025-12-08",
      cat8: 24,
      cat8Cough: 3,
      cat8Phlegm: 3,
      cat8ChestTightness: 3,
      cat8Breathlessness: 3,
      cat8Activities: 3,
      cat8Confidence: 3,
      cat8Sleep: 3,
      cat8Energy: 3,
      moderateExacerbations: false,
      seriousExacerbations: true,
      physicalActivity: 1,
      weight: 80,
      note: "Innlagt på sykehus to dager.",
      medicines: [1, 2],
      medicinesAtc: ["R03AC02", "R03BA02"],
      medicinesDoses: [2, 1],
      medicinesUsedTimes: [7, 3],
    },
    {
      date: "2025-12-15",
      cat8: 19,
      cat8Cough: 2,
      cat8Phlegm: 3,
      cat8ChestTightness: 2,
      cat8Breathlessness: 3,
      cat8Activities: 2,
      cat8Confidence: 3,
      cat8Sleep: 2,
      cat8Energy: 2,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 2,
      weight: 80,
      note: "",
      medicines: [1],
      medicinesAtc: ["R03AC02"],
      medicinesDoses: [2],
      medicinesUsedTimes: [3],
    },
    {
      date: "2025-12-22",
      cat8: 15,
      cat8Cough: 2,
      cat8Phlegm: 2,
      cat8ChestTightness: 2,
      cat8Breathlessness: 2,
      cat8Activities: 2,
      cat8Confidence: 2,
      cat8Sleep: 2,
      cat8Energy: 1,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 2,
      weight: 81,
      note: "Jul med familien, litt mer aktivitet.",
      medicines: [1],
      medicinesAtc: ["R03AC02"],
      medicinesDoses: [2],
      medicinesUsedTimes: [2],
    },
    {
      date: "2025-12-29",
      cat8: 13,
      cat8Cough: 2,
      cat8Phlegm: 1,
      cat8ChestTightness: 2,
      cat8Breathlessness: 2,
      cat8Activities: 2,
      cat8Confidence: 1,
      cat8Sleep: 2,
      cat8Energy: 1,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 3,
      weight: 81,
      note: "",
      medicines: [],
      medicinesAtc: [],
      medicinesDoses: [],
      medicinesUsedTimes: [],
    },
    {
      date: "2026-01-05",
      cat8: 17,
      cat8Cough: 2,
      cat8Phlegm: 2,
      cat8ChestTightness: 2,
      cat8Breathlessness: 3,
      cat8Activities: 2,
      cat8Confidence: 2,
      cat8Sleep: 2,
      cat8Energy: 2,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 2,
      weight: 82,
      note: "Kaldt vær, holder meg mest inne.",
      medicines: [1],
      medicinesAtc: ["R03AC02"],
      medicinesDoses: [2],
      medicinesUsedTimes: [2],
    },
    {
      date: "2026-01-12",
      cat8: 21,
      cat8Cough: 3,
      cat8Phlegm: 3,
      cat8ChestTightness: 2,
      cat8Breathlessness: 3,
      cat8Activities: 3,
      cat8Confidence: 2,
      cat8Sleep: 3,
      cat8Energy: 2,
      moderateExacerbations: true,
      seriousExacerbations: false,
      physicalActivity: 1,
      weight: 81,
      note: "",
      medicines: [1, 2],
      medicinesAtc: ["R03AC02", "R03BA02"],
      medicinesDoses: [2, 1],
      medicinesUsedTimes: [6, 2],
    },
    {
      date: "2026-01-19",
      cat8: 16,
      cat8Cough: 2,
      cat8Phlegm: 2,
      cat8ChestTightness: 2,
      cat8Breathlessness: 2,
      cat8Activities: 2,
      cat8Confidence: 2,
      cat8Sleep: 2,
      cat8Energy: 2,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 2,
      weight: 82,
      note: "",
      medicines: [1],
      medicinesAtc: ["R03AC02"],
      medicinesDoses: [2],
      medicinesUsedTimes: [3],
    },
    {
      date: "2026-01-26",
      cat8: 14,
      cat8Cough: 2,
      cat8Phlegm: 2,
      cat8ChestTightness: 2,
      cat8Breathlessness: 2,
      cat8Activities: 2,
      cat8Confidence: 1,
      cat8Sleep: 2,
      cat8Energy: 1,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 3,
      weight: 82,
      note: "Kjenner bedring gradvis.",
      medicines: [1],
      medicinesAtc: ["R03AC02"],
      medicinesDoses: [2],
      medicinesUsedTimes: [2],
    },
    {
      date: "2026-02-02",
      cat8: 10,
      cat8Cough: 1,
      cat8Phlegm: 1,
      cat8ChestTightness: 1,
      cat8Breathlessness: 2,
      cat8Activities: 1,
      cat8Confidence: 1,
      cat8Sleep: 2,
      cat8Energy: 1,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 3,
      weight: 83,
      note: "",
      medicines: [],
      medicinesAtc: [],
      medicinesDoses: [],
      medicinesUsedTimes: [],
    },
    {
      date: "2026-02-09",
      cat8: 7,
      cat8Cough: 1,
      cat8Phlegm: 1,
      cat8ChestTightness: 1,
      cat8Breathlessness: 1,
      cat8Activities: 1,
      cat8Confidence: 1,
      cat8Sleep: 1,
      cat8Energy: 0,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 3,
      weight: 83,
      note: "Beste uka på lenge!",
      medicines: [],
      medicinesAtc: [],
      medicinesDoses: [],
      medicinesUsedTimes: [],
    },
    {
      date: "2026-02-16",
      cat8: 12,
      cat8Cough: 2,
      cat8Phlegm: 1,
      cat8ChestTightness: 2,
      cat8Breathlessness: 1,
      cat8Activities: 2,
      cat8Confidence: 1,
      cat8Sleep: 2,
      cat8Energy: 1,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 3,
      weight: 83,
      note: "",
      medicines: [1],
      medicinesAtc: ["R03AC02"],
      medicinesDoses: [2],
      medicinesUsedTimes: [1],
    },
    {
      date: "2026-02-23",
      cat8: 26,
      cat8Cough: 3,
      cat8Phlegm: 5,
      cat8ChestTightness: 2,
      cat8Breathlessness: 4,
      cat8Activities: 4,
      cat8Confidence: 2,
      cat8Sleep: 3,
      cat8Energy: 3,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 2,
      weight: 82,
      note: "Litt sliten etter helgen.",
      medicines: [1],
      medicinesAtc: ["R03AC02"],
      medicinesDoses: [2],
      medicinesUsedTimes: [2],
    },
    {
      date: "2026-03-02",
      cat8: 15,
      cat8Cough: 2,
      cat8Phlegm: 2,
      cat8ChestTightness: 2,
      cat8Breathlessness: 2,
      cat8Activities: 2,
      cat8Confidence: 2,
      cat8Sleep: 2,
      cat8Energy: 1,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 3,
      weight: 82,
      note: "",
      medicines: [1],
      medicinesAtc: ["R03AC02"],
      medicinesDoses: [2],
      medicinesUsedTimes: [2],
    },
    {
      date: "2026-03-09",
      cat8: 40,
      cat8Cough: 5,
      cat8Phlegm: 5,
      cat8ChestTightness: 5,
      cat8Breathlessness: 5,
      cat8Activities: 5,
      cat8Confidence: 5,
      cat8Sleep: 5,
      cat8Energy: 5,
      moderateExacerbations: true,
      seriousExacerbations: false,
      physicalActivity: 2,
      weight: 81,
      note: "Mer hoste denne uken.",
      medicines: [1, 2],
      medicinesAtc: ["R03AC02", "R03BA02"],
      medicinesDoses: [2, 1],
      medicinesUsedTimes: [5, 1],
    },
    {
      date: "2026-03-16",
      cat8: 13,
      cat8Cough: 2,
      cat8Phlegm: 1,
      cat8ChestTightness: 2,
      cat8Breathlessness: 2,
      cat8Activities: 1,
      cat8Confidence: 2,
      cat8Sleep: 2,
      cat8Energy: 1,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 3,
      weight: 82,
      note: "",
      medicines: [1],
      medicinesAtc: ["R03AC02"],
      medicinesDoses: [2],
      medicinesUsedTimes: [2],
    },
    {
      date: "2026-03-23",
      cat8: 10,
      cat8Cough: 1,
      cat8Phlegm: 1,
      cat8ChestTightness: 1,
      cat8Breathlessness: 2,
      cat8Activities: 1,
      cat8Confidence: 2,
      cat8Sleep: 1,
      cat8Energy: 1,
      moderateExacerbations: false,
      seriousExacerbations: false,
      physicalActivity: 3,
      weight: 82,
      note: "Vår er på vei, humøret bedre.",
      medicines: [1],
      medicinesAtc: ["R03AC02"],
      medicinesDoses: [2],
      medicinesUsedTimes: [1],
    },
  ],
  medicines: [
    { id: 1, name: "Ventolin", atcCode: "R03AC02", ingredients: [] },
    { id: 2, name: "Pulmicort", atcCode: "R03BA02", ingredients: [] },
  ],
  userMedicines: [
    {
      medicineId: 1,
      reason: "Fast medisin",
      dose: "2 puff",
      startedUsage: "2024-01-15",
      stoppedUsage: null,
      medicine: {
        id: 1,
        name: "Ventolin",
        type: 1,
        availableDoses: "2 puff",
        image: null,
      },
    },
    {
      medicineId: 2,
      reason: "Ved behov",
      dose: "1 puff",
      startedUsage: "2024-06-01",
      stoppedUsage: null,
      medicine: {
        id: 2,
        name: "Pulmicort",
        type: 2,
        availableDoses: "1 puff",
        image: null,
      },
    },
  ],
  latestGad7: {
    date: "2026-03-23",
    feelingNervous: 1,
    noWorryingControl: 2,
    worrying: 1,
    troubleRelaxing: 1,
    restless: 0,
    easilyAnnoyed: 1,
    afraid: 0,
  },
  latestMedicineSatisfaction: {
    date: "2026-03-23",
    medicines: [
      { medicineId: 1, satisfaction: 4 },
      { medicineId: 2, satisfaction: 3 },
    ],
  },
  scores: {},
  questionnaires: [],
  advice: [],
  gad7History: [
    {
      date: "2025-10-15",
      feelingNervous: 3,
      noWorryingControl: 1,
      worrying: 0,
      troubleRelaxing: 0,
      restless: 0,
      easilyAnnoyed: 3,
      afraid: 1,
    },
    {
      date: "2025-11-12",
      feelingNervous: 2,
      noWorryingControl: 2,
      worrying: 0,
      troubleRelaxing: 3,
      restless: 3,
      easilyAnnoyed: 0,
      afraid: 0,
    },
    {
      date: "2025-12-10",
      feelingNervous: 0,
      noWorryingControl: 1,
      worrying: 0,
      troubleRelaxing: 1,
      restless: 1,
      easilyAnnoyed: 3,
      afraid: 0,
    },
    {
      date: "2026-01-14",
      feelingNervous: 0,
      noWorryingControl: 1,
      worrying: 0,
      troubleRelaxing: 1,
      restless: 0,
      easilyAnnoyed: 1,
      afraid: 1,
    },
    {
      date: "2026-02-11",
      feelingNervous: 0,
      noWorryingControl: 0,
      worrying: 1,
      troubleRelaxing: 1,
      restless: 0,
      easilyAnnoyed: 1,
      afraid: 0,
    },
    {
      date: "2026-03-11",
      feelingNervous: 0,
      noWorryingControl: 1,
      worrying: 0,
      troubleRelaxing: 1,
      restless: 0,
      easilyAnnoyed: 1,
      afraid: 1,
    },
    {
      date: "2026-04-01",
      feelingNervous: 0,
      noWorryingControl: 0,
      worrying: 0,
      troubleRelaxing: 1,
      restless: 0,
      easilyAnnoyed: 0,
      afraid: 0,
    },
  ],
  phq9History: [
    {
      date: "2025-10-15",
      noPleasureDoingThings: 1,
      depressed: 0,
      stayingAsleep: 1,
      noEnergy: 2,
      noAppetite: 0,
      selfPity: 0,
      troubleConcentration: 3,
      slowMovingSpeeking: 1,
      suicidal: 0,
    },
    {
      date: "2025-11-12",
      noPleasureDoingThings: 1,
      depressed: 0,
      stayingAsleep: 2,
      noEnergy: 3,
      noAppetite: 3,
      selfPity: 1,
      troubleConcentration: 0,
      slowMovingSpeeking: 0,
      suicidal: 0,
    },
    {
      date: "2025-12-10",
      noPleasureDoingThings: 3,
      depressed: 0,
      stayingAsleep: 1,
      noEnergy: 0,
      noAppetite: 0,
      selfPity: 1,
      troubleConcentration: 1,
      slowMovingSpeeking: 1,
      suicidal: 0,
    },
    {
      date: "2026-01-14",
      noPleasureDoingThings: 1,
      depressed: 0,
      stayingAsleep: 0,
      noEnergy: 1,
      noAppetite: 1,
      selfPity: 1,
      troubleConcentration: 0,
      slowMovingSpeeking: 1,
      suicidal: 0,
    },
    {
      date: "2026-02-11",
      noPleasureDoingThings: 0,
      depressed: 1,
      stayingAsleep: 0,
      noEnergy: 1,
      noAppetite: 0,
      selfPity: 0,
      troubleConcentration: 1,
      slowMovingSpeeking: 1,
      suicidal: 0,
    },
    {
      date: "2026-03-11",
      noPleasureDoingThings: 1,
      depressed: 0,
      stayingAsleep: 0,
      noEnergy: 1,
      noAppetite: 1,
      selfPity: 1,
      troubleConcentration: 0,
      slowMovingSpeeking: 1,
      suicidal: 0,
    },
    {
      date: "2026-04-01",
      noPleasureDoingThings: 2,
      depressed: 0,
      stayingAsleep: 0,
      noEnergy: 1,
      noAppetite: 1,
      selfPity: 0,
      troubleConcentration: 0,
      slowMovingSpeeking: 1,
      suicidal: 0,
    },
  ],
};
