image: node:20

definitions:
  caches:
    node: node_modules

pipelines:
  default:
    - step:
        name: Install & Lint
        caches:
          - node
        script:
          - npm ci
          - npm run lint

  branches:
    testing:
      - step:
          name: Install, Lint & Test
          caches:
            - node
          script:
            - npm ci
            - npm run lint
            - npm test -- --watchAll=false --passWithNoTests

    main:
      - step:
          name: Install, Lint & Test
          caches:
            - node
          script:
            - npm ci
            - npm run lint
            - npm test -- --watchAll=false --passWithNoTests
      - step:
          name: Build
          caches:
            - node
          script:
            - npm ci
            - npm run build
          artifacts:
            - .next/**
